// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZK3z2XwGe5QokgMHaBYjupWmSi81Loc',
    appId: '1:852677245030:web:dcb625943f7f7150bdd5a7',
    messagingSenderId: '852677245030',
    projectId: 'flutter-d6303',
    authDomain: 'flutter-d6303.firebaseapp.com',
    storageBucket: 'flutter-d6303.firebasestorage.app',
    measurementId: 'G-WLC1Q8JC0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WQV04GYGHF4RhXTjYciUviDl3A4K-YM',
    appId: '1:852677245030:android:e06db90ec879d978bdd5a7',
    messagingSenderId: '852677245030',
    projectId: 'flutter-d6303',
    storageBucket: 'flutter-d6303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKuCdAjhM40ESMKehvMhy_c0qe0w4CidQ',
    appId: '1:852677245030:ios:05bd40f77c231d1abdd5a7',
    messagingSenderId: '852677245030',
    projectId: 'flutter-d6303',
    storageBucket: 'flutter-d6303.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKuCdAjhM40ESMKehvMhy_c0qe0w4CidQ',
    appId: '1:852677245030:ios:05bd40f77c231d1abdd5a7',
    messagingSenderId: '852677245030',
    projectId: 'flutter-d6303',
    storageBucket: 'flutter-d6303.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZK3z2XwGe5QokgMHaBYjupWmSi81Loc',
    appId: '1:852677245030:web:1205d87bc2001033bdd5a7',
    messagingSenderId: '852677245030',
    projectId: 'flutter-d6303',
    authDomain: 'flutter-d6303.firebaseapp.com',
    storageBucket: 'flutter-d6303.firebasestorage.app',
    measurementId: 'G-V2BSTQT8JG',
  );
}
